# Generated by Django 5.2.4 on 2025-07-05 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_product_cartuser_product_paymentmethod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='paymentMethod',
        ),
    ]
